# Build project
FROM node:19.3 AS build

WORKDIR /app

COPY package*.json ./

RUN npm install --force

COPY . .
# override config with mainnet config
RUN cp /app/config-mainnet.json /app/src/constants/config.json
RUN ./google_analytics_setup.sh mainnet

RUN npm run build

# Setup Nginx
FROM nginx:1.23

COPY --from=build /app/build /usr/share/nginx/html

RUN rm /etc/nginx/nginx.conf

COPY nginx.conf /etc/nginx/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
